# Generated by Django 4.2.7 on 2025-03-23 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='教师工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='other', max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='专业特长')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='入职日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'ordering': ['-join_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100, verbose_name='证书名称')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='证书编号')),
                ('issue_date', models.DateField(verbose_name='颁发日期')),
                ('issue_organization', models.CharField(max_length=100, verbose_name='颁发机构')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='证书图片')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='teachers.teacher')),
            ],
            options={
                'verbose_name': '教师证书',
                'verbose_name_plural': '教师证书',
                'ordering': ['-issue_date'],
            },
        ),
    ]
