# Generated by Django 4.2.7 on 2025-04-01 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='teachers/avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('specialties', models.JSONField(default=list, verbose_name='教学专长')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
        migrations.CreateModel(
            name='TeacherCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='证书名称')),
                ('issue_date', models.DateField(verbose_name='发证日期')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('issuing_authority', models.CharField(max_length=100, verbose_name='发证机构')),
                ('certificate_no', models.CharField(blank=True, max_length=50, verbose_name='证书编号')),
                ('image', models.ImageField(upload_to='teachers/certificates/', verbose_name='证书图片')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已验证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': '教师证书',
                'verbose_name_plural': '教师证书',
            },
        ),
        migrations.CreateModel(
            name='PrivacySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_visibility', models.CharField(choices=[('self', '仅自己可见'), ('students', '仅学生可见'), ('all', '所有人可见')], default='self', max_length=10, verbose_name='手机号可见性')),
                ('email_visibility', models.CharField(choices=[('self', '仅自己可见'), ('students', '仅学生可见'), ('all', '所有人可见')], default='self', max_length=10, verbose_name='邮箱可见性')),
                ('bio_visibility', models.CharField(choices=[('self', '仅自己可见'), ('students', '仅学生可见'), ('all', '所有人可见')], default='all', max_length=10, verbose_name='简介可见性')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_setting', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': '隐私设置',
                'verbose_name_plural': '隐私设置',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_reminder', models.BooleanField(default=True, verbose_name='课程提醒')),
                ('attendance_reminder', models.BooleanField(default=True, verbose_name='考勤提醒')),
                ('fee_reminder', models.BooleanField(default=True, verbose_name='学费提醒')),
                ('in_app', models.BooleanField(default=True, verbose_name='站内消息')),
                ('sms', models.BooleanField(default=False, verbose_name='短信通知')),
                ('email', models.BooleanField(default=False, verbose_name='邮件通知')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': '通知设置',
                'verbose_name_plural': '通知设置',
            },
        ),
    ]
