# Generated by Django 4.2.7 on 2025-04-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
    ]
