# Generated by Django 4.2.7 on 2025-04-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacherprofile_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherCertificate',
        ),
    ]
