# Generated by Django 4.2.7 on 2025-04-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicerecord',
            name='status',
            field=models.CharField(choices=[('active', '练琴中'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='practicerecord',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='练习时长(分钟)'),
        ),
        migrations.AlterField(
            model_name='practicerecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
    ]
