# Generated by Django 4.2.7 on 2025-04-06 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancesession_is_active_and_more'),
        ('students', '0002_practicerecord_status_alter_practicerecord_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-check_in_time'], 'verbose_name': '旧版考勤记录', 'verbose_name_plural': '旧版考勤记录'},
        ),
        migrations.AddField(
            model_name='practicerecord',
            name='attendance_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_records', to='attendance.attendancesession', verbose_name='关联考勤会话'),
        ),
    ]
