# Generated by Django 4.2.7 on 2025-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_pianolevel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='is_temporary',
            field=models.BooleanField(default=False, verbose_name='是否临时'),
        ),
    ]
