# Generated by Django 4.2.7 on 2025-04-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseschedule_is_temporary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': '课程时间表', 'verbose_name_plural': '课程时间表'},
        ),
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='is_temporary',
            field=models.BooleanField(default=False, verbose_name='临时排课'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='weekday',
            field=models.IntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], verbose_name='星期'),
        ),
        migrations.AddConstraint(
            model_name='courseschedule',
            constraint=models.UniqueConstraint(fields=('course', 'weekday', 'start_time'), name='unique_course_schedule'),
        ),
    ]
