# Generated by Django 4.2.7 on 2025-04-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_delete_teachercertificate'),
        ('courses', '0005_piano_is_reserved_piano_reserved_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teachers.teacherprofile', verbose_name='教师'),
        ),
    ]
