# Generated by Django 4.2.7 on 2025-03-23 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('category_type', models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=10, verbose_name='类别类型')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '支付类别',
                'verbose_name_plural': '支付类别',
            },
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应缴金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已缴金额')),
                ('status', models.CharField(choices=[('pending', '待缴费'), ('partial', '部分缴费'), ('paid', '已缴费'), ('overdue', '逾期'), ('refunded', '已退款')], default='pending', max_length=10, verbose_name='状态')),
                ('due_date', models.DateField(verbose_name='截止日期')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='缴费日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to='courses.course', verbose_name='课程')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuition', to='courses.enrollment', verbose_name='报名记录')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学费记录',
                'verbose_name_plural': '学费记录',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='TuitionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='缴费金额')),
                ('payment_type', models.CharField(choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('bank_transfer', '银行转账'), ('other', '其他')], default='cash', max_length=20, verbose_name='支付方式')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='缴费日期')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='收据号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_tuition_payments', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('tuition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.tuition', verbose_name='学费记录')),
            ],
            options={
                'verbose_name': '学费支付记录',
                'verbose_name_plural': '学费支付记录',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('payment_type', models.CharField(choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('bank_transfer', '银行转账'), ('other', '其他')], default='cash', max_length=20, verbose_name='支付方式')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='支付日期')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='收据号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.paymentcategory', verbose_name='类别')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.course', verbose_name='课程')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='students.student', verbose_name='学生')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_payments', to='teachers.teacher', verbose_name='教师')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('expense_type', models.CharField(choices=[('rent', '房租'), ('utility', '水电费'), ('salary', '工资'), ('maintenance', '维修费'), ('purchase', '采购费'), ('tax', '税费'), ('insurance', '保险费'), ('marketing', '营销费'), ('other', '其他')], max_length=20, verbose_name='支出类型')),
                ('payment_type', models.CharField(choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('bank_transfer', '银行转账'), ('other', '其他')], default='cash', max_length=20, verbose_name='支付方式')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='支出日期')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='发票号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_expenses', to='teachers.teacher', verbose_name='教师')),
            ],
            options={
                'verbose_name': '支出记录',
                'verbose_name_plural': '支出记录',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
