# Generated by Django 4.2.7 on 2025-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='二维码字符串'),
        ),
    ]
