# Generated by Django 4.2.7 on 2025-04-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_qrcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]
