# Generated by Django 4.2.7 on 2025-04-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_attendance_options_and_more'),
        ('courses', '0004_alter_courseschedule_options_and_more'),
        ('attendance', '0005_attendancesession_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PianoAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_time', models.DateTimeField(auto_now_add=True, verbose_name='预留时间')),
                ('expiration_time', models.DateTimeField(verbose_name='预留过期时间')),
                ('status', models.CharField(choices=[('reserved', '已预留'), ('assigned', '已分配'), ('expired', '已过期'), ('cancelled', '已取消')], default='reserved', max_length=20, verbose_name='状态')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.piano')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piano_assignments', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piano_assignments', to='students.student')),
            ],
            options={
                'verbose_name': '钢琴分配',
                'verbose_name_plural': '钢琴分配',
                'ordering': ['reserved_time'],
            },
        ),
    ]
