# Generated by Django 4.2.7 on 2025-04-08 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_attendance_options_and_more'),
        ('attendance', '0006_pianoassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingqueue',
            name='practice_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_queue_record', to='students.practicerecord', verbose_name='关联练琴记录'),
        ),
    ]
